# Cf. https://github.com/systemd/mkosi/blob/main/mkosi/resources/man/mkosi.1.md
# For details on each section of this config file
[Content]
Bootable=no
RootPassword=root
Locale=C.UTF-8
Timezone=Europe/Paris
Keymap=fr
RemoveFiles=/etc/yum.repos.d/mkosi.repo
# List of packages to be installed on the target
Packages=atf,kernel,redpesk-bsp-repos-config,optee-os,optee-client,optee-test,solidrun-firmware,uboot
Packages=NetworkManager-wifi,audit,audit-rules,can-tests,can-utils,chkconfig,chrony,cronie,cronie-anacron,crontabs,dbus-libs,default-fonts-core-sans,diffutils,dmidecode,dnf-plugins-core
Packages=dracut-chsmack,dracut-live,dracut-redpesk-common,dtc,duktape,dwz,e2fsprogs,e2fsprogs-libs,efi-srpm-macros,ethtool,file
Packages=firewalld,firewalld-filesystem,fonts-filesystem,fonts-srpm-macros,forge-srpm-macros,fuse3-libs,glibc-gconv-extra,glibc-langpack-en 
Packages=go-srpm-macros,groff-base,hdparm,hostname,hwdata,i2c-tools,inih,initscripts,initscripts-rename-device,initscripts-service
Packages=iptables-libs,iputils,irqbalance,iw,jansson,jitterentropy,jq,kernel-srpm-macros,kexec-tools,langpacks-core-en_GB,langpacks-en_GB,langpacks-fonts-en
Packages=less,libcbor,libedit,libfdt,libfido2,libi2c,libnetfilter_conntrack,libnfnetlink,libnftnl,libmnl,libpipeline
Packages=libselinux-utils,libss,libsss_idmap,libsss_nss_idmap,libusb1,linux-firmware-amphion,linux-firmware-imx,lua-srpm-macros,man-db
Packages=ncurses,nftables,numactl-libs,ocaml-srpm-macros,oniguruma,openblas-srpm-macros,openssh-clients,openssl1.1
Packages=package-notes-srpm-macros,parted,perl-srpm-macros,picocom,platform-firstboot,platform-runtime-tools,policycoreutils
Packages=polkit,polkit-libs,pyproject-srpm-macros,python-srpm-macros,python3-dateutil,python3-dbus,python3-dnf-plugins-core,python3-firewall
Packages=python3-gobject-base,python3-gobject-base-noarch,python3-inotify,python3-linux-procfs,python3-nftables,python3-pyudev,python3-six
Packages=python3-systemd,qt6-srpm-macros,redhat-mono-vf-fonts,redhat-rpm-config,redhat-text-vf-fonts,redpesk-bsp-repos-corn,redpesk-repos-config
Packages=rng-tools,rootfiles,rust-toolset-srpm-macros,sssd-client,sudo,tar,tree,tuned,uboot-tools,unzip,usbutils,userspace-rcu
Packages=virt-what,wget,wireless-regdb,wpa_supplicant,xfsprogs,yum,yum-utils,zip
Packages=NetworkManager,vim,dnf,iproute,vim-minimal,openssh-server
Packages=afb-app-manager,afb-app-manager-rpm,afb-binder,sec-lsm-manager-smack,sec-smack-rules
# Creation of U-Boot bootscript (instead inside U-Boot package)
PostInstallationScripts=scripts/postinstall/30-uboot-scr.sh
# Copy and flash the bootloader to the image
FinalizeScripts=scripts/finalize/00-copy-uboot.sh
PostOutputScripts=scripts/postoutput/00-flash-uboot.sh
# Creation an archive of the image + bmapfile for flashing
PostOutputScripts=scripts/postoutput/99-redpesk.sh
# Extract installed packages list
FinalizeScripts=scripts/finalize/50-manifest.sh
PostInstallationScripts=scripts/postinstall/50-binding-firstboot.sh

[Distribution]
Architecture=arm64
Distribution=rocky # for compatibility
Release=10

[Build]
# Specific options for the /boot partition creation
Environment=SYSTEMD_REPART_MKFS_OPTIONS_VFAT="-S 512 -F 32"
# Specific options for flashing the bootloader
Environment=REDPESK_BSP=solidrun-hummingboard-bsp
Environment=REDPESK_FLASH_BINS=/boot/flash.bin:bs=1024,seek=32,conv=notrunc
Environment=UBOOT_DIR=tmp/uboot<
# Installation of helloworld-binding
Environment=REDPESK_BINDING_LIST=helloworld-binding
WithNetwork=yes

[Output]
Format=disk
OutputDirectory=output

[Validation]
Checksum=yes
