# Cf. https://github.com/systemd/mkosi/blob/main/mkosi/resources/man/mkosi.1.md
# For details on each section of this config file
[Content]
Bootable=no
RootPassword=root
Locale=C.UTF-8
Timezone=Europe/Paris
Keymap=fr
RemoveFiles=/etc/yum.repos.d/mkosi.repo
# List of packages to be installed on the target
Packages=kernel,uboot-smack,uboot,bcm2711-firmware,bcm2835-firmware
Packages=NetworkManager,vim,dnf,iproute,vim-minimal,openssh-server
Packages=afb-app-manager,afb-app-manager-rpm,afb-binder,sec-lsm-manager-smack,sec-smack-rules
# Creation an archive of the image + bmapfile for flashing
PostOutputScripts=scripts/postoutput/99-redpesk.sh

[Distribution]
Architecture=arm64
Distribution=rocky # for compatibility
Release=10

[Build]
# Specific options for the /boot partition creation
Environment=SYSTEMD_REPART_MKFS_OPTIONS_VFAT="-S 512 -F 32"
WithNetwork=yes

[Output]
Format=disk
OutputDirectory=output

[Validation]
Checksum=yes
