[Content]
Bootable=no
RootPassword=root
Locale=C.UTF-8
Timezone=Europe/Paris
Keymap=fr
RemoveFiles=/etc/yum.repos.d/mkosi.repo

Packages=kernel,uboot-smack,uboot,bcm2711-firmware,bcm2835-firmware
Packages=NetworkManager,vim,dnf,iproute,vim-minimal,openssh-server
Packages=afb-app-manager,afb-app-manager-rpm,afb-binder,sec-lsm-manager-smack,sec-smack-rules
#PostInstallationScripts=scripts/postinstall/50-copykernelimage.sh


[Distribution]
Architecture=arm64
Distribution=rocky # for compatibility
Release=10

[Build]
Environment=SYSTEMD_REPART_MKFS_OPTIONS_VFAT="-S 512 -F 32"
WithNetwork=yes

[Output]
Format=disk
OutputDirectory=output

[Validation]
Checksum=yes
