# Cf. https://github.com/systemd/mkosi/blob/main/mkosi/resources/man/mkosi.1.md
# For details on each section of this config file
[Content]
Bootable=no
RootPassword=root
Locale=C.UTF-8
Timezone=Europe/Paris
Keymap=fr
RemoveFiles=/etc/yum.repos.d/mkosi.repo
# List of packages to be installed on the target
Packages=atf,kernel,redpesk-bsp-repos-config,solidrun-firmware,uboot
Packages=NetworkManager,vim,dnf,iproute,vim-minimal,openssh-server
Packages=afb-app-manager,afb-app-manager-rpm,afb-binder,sec-lsm-manager-smack,sec-smack-rules
# Creation of U-Boot bootscript (instead inside U-Boot package)
PostInstallationScripts=scripts/postinstall/30-uboot-scr.sh
# Copy and flash the bootloader to the image
FinalizeScripts=scripts/finalize/00-copy-uboot.sh
PostOutputScripts=scripts/postoutput/00-flash-uboot.sh
# Creation an archive of the image + bmapfile for flashing
PostOutputScripts=scripts/postoutput/99-redpesk.sh

[Distribution]
Architecture=arm64
Distribution=rocky # for compatibility
Release=10

[Build]
# Specific options for the /boot partition creation
Environment=SYSTEMD_REPART_MKFS_OPTIONS_VFAT="-S 512 -F 32"
# Specific options for flashing the bootloader
Environment=REDPESK_BSP=solidrun-hummingboard-bsp
Environment=REDPESK_FLASH_BINS=/boot/flash.bin:bs=1024,seek=32,conv=notrunc
Environment=UBOOT_DIR=tmp/uboot
WithNetwork=yes

[Output]
Format=disk
OutputDirectory=output

[Validation]
Checksum=yes
